### ISSUE TITLE
install proto files using cmake module

### ISSUE THREAD

**Issue by yuzhangbit** [yuzhangbit/port_apollo#1]
The .proto files need to be installed to the shared folder for importing.

**Comment by Youngjin-Hyun** [comment]
HI, I am really impressed with your effort.
I am trying to port 'map' and 'perception' in the modules.
But I have some problems with building proto files.
First, Import other proto files problems.
I added Proto_import_DIRS sentences in the FindProtobuf.cmake file.
So proto files generated pb.h files fortunately.
But the generated pb.h files, must include generated pb.h path, But it don't.
Could you please give me some advice.
Thank you.

**Comment by JongMinLee86** [comment]
HI, I am really impressed with your effort.
I am trying to port 'map' and 'perception' in the modules.
But I have some problems with building proto files.
First, Import other proto files problems.
I added Proto_import_DIRS sentences in the FindProtobuf.cmake file.
So proto files generated pb.h files fortunately.
But the generated pb.h files, must include generated pb.h path, But it don't.
Could you please give me some advice.
.proto files need to be installed to the shared folder??
I don't understand about shared folder. An example is truly helpful.
Thank you.

**Comment by yuzhangbit** [comment]
@JongMinLee86  The generated header files and source files are collected by `PROTO_HDRS` and `PROTO_SRCS` variables.  You can find examples [here](https://github.com/yuzhangbit/port_apollo/blob/master/src/common/CMakeLists.txt#L38)

The share folder is just a place to save the original proto files for reference.   

The project is deprecated. Please refer to the new one [https://github.com/yuzhangbit/apollo_standalone](https://github.com/yuzhangbit/apollo_standalone). It uses the modern cmake style and has a better project structure.
